//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan_LKS_Laundry_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailtransaction
    {
        public Nullable<int> id_service { get; set; }
        public int id_header_transaction { get; set; }
        public int id_detail_transaction { get; set; }
        public Nullable<int> id_package { get; set; }
        public int price_detail_transaction { get; set; }
        public float total_unit_detail_transaction { get; set; }
        public Nullable<System.DateTime> complete_datetime_detail_transaction { get; set; }
    
        public virtual headertransaction headertransaction { get; set; }
        public virtual package package { get; set; }
        public virtual service service { get; set; }
    }
}
