//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan_LKS_Laundry_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public int id_discount { get; set; }
        public string discount_name { get; set; }
        public string discount_for { get; set; }
        public int discount1 { get; set; }
    }
}
