//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan_LKS_Laundry_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.headertransactions = new HashSet<headertransaction>();
        }
    
        public int id_job { get; set; }
        public int id_employee { get; set; }
        public string password_employee { get; set; }
        public string name_employee { get; set; }
        public string email_employee { get; set; }
        public string addres_employee { get; set; }
        public string phone_number_employee { get; set; }
        public System.DateTime date_of_birth_employee { get; set; }
        public decimal salary_employee { get; set; }
    
        public virtual job job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<headertransaction> headertransactions { get; set; }
    }
}
