//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan_LKS_Laundry_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class headertransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public headertransaction()
        {
            this.detailtransactions = new HashSet<detailtransaction>();
        }
    
        public int id_employee { get; set; }
        public int id_customer { get; set; }
        public int id_header_transaction { get; set; }
        public System.DateTime transaction_date_time_header_transaction { get; set; }
        public Nullable<System.DateTime> complete_estimation_date_time_header { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailtransaction> detailtransactions { get; set; }
        public virtual employee employee { get; set; }
    }
}
