//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latihan_LKS_Laundry_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaundryEntities : DbContext
    {
        public LaundryEntities()
            : base("name=LaundryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<detailpackage> detailpackages { get; set; }
        public virtual DbSet<detailtransaction> detailtransactions { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<headertransaction> headertransactions { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<unit> units { get; set; }
    }
}
